[phases.setup]
nixPkgs = ["nodejs_20", "python312Full"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python3 -m gunicorn app:app --bind 0.0.0.0:$PORT"
